import os
import time
import copy
import random
import argparse
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
from torch.cuda.amp import GradScaler, autocast

import torchvision
from torchvision import models
from torchvision.transforms import v2

import numpy as np
import pandas as pd
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns

from sklearn.model_selection import GroupShuffleSplit, train_test_split
from sklearn.metrics import (
    confusion_matrix, roc_curve, roc_auc_score,
    accuracy_score, precision_score, recall_score, f1_score
)
from torch.optim.lr_scheduler import CosineAnnealingLR

# ==========================================
# 1. REPRODUCIBILITY & SETUP
# ==========================================

def seed_everything(seed=42):
    """
    Initialize global seeds for reproducibility and enable deterministic algorithms
    in PyTorch to ensure identical runs.
    """
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    
    # Configure PyTorch to use deterministic algorithms
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    
    # Enable deterministic behavior in PyTorch
    # warn_only=True generates a runtime warning instead of crashing on non-deterministic ops
    torch.use_deterministic_algorithms(True, warn_only=True)
    os.environ['CUBLAS_WORKSPACE_CONFIG'] = ':4096:8'

seed_everything(42)

# ==========================================
# 2. CUSTOM LOSS FUNCTION
# ==========================================

class WeightedSoftCELoss(nn.Module):
    """
    Custom Cross-Entropy Loss that supports class-weighting, label smoothing,
    and handles both integer labels and soft labels (generated by CutMix/MixUp).
    """
    def __init__(self, weight=None, label_smoothing=0.1):
        super().__init__()
        self.weight = weight
        self.label_smoothing = label_smoothing

    def forward(self, logits, targets):
        num_classes = logits.size(-1)
        log_probs = F.log_softmax(logits, dim=-1)

        # Handle standard integer labels
        if targets.ndim == 1:
            smooth_targets = torch.full_like(log_probs, self.label_smoothing / num_classes)
            smooth_targets.scatter_(1, targets.unsqueeze(1), 1.0 - self.label_smoothing + (self.label_smoothing / num_classes))
        # Handle soft targets (CutMix/MixUp outputs)
        else:
            smooth_targets = targets * (1.0 - self.label_smoothing) + self.label_smoothing / num_classes

        # Apply class weights
        if self.weight is not None:
            weighted_log_probs = log_probs * self.weight.unsqueeze(0)
            loss = -(smooth_targets * weighted_log_probs).sum(dim=-1).mean()
        else:
            loss = -(smooth_targets * log_probs).sum(dim=-1).mean()
        return loss

# ==========================================
# 3. PREPROCESSING & DATASET
# ==========================================

class ISICDataset(Dataset):
    """
    Custom PyTorch Dataset for loading ISIC 2019 images.
    """
    def __init__(self, df, img_dir, transform=None):
        self.df = df.reset_index(drop=True)
        self.img_dir = Path(img_dir)
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        img_name = self.df.loc[idx, 'image']
        label = int(self.df.loc[idx, 'label'])
        
        # Check multiple extensions
        img_path = None
        for ext in ['.jpg', '.jpeg', '.png', '.JPG']:
            path = self.img_dir / (img_name + ext)
            if path.exists():
                img_path = path
                break
        
        if img_path is None:
            raise FileNotFoundError(f"Image {img_name} not found in {self.img_dir}")
            
        image = Image.open(img_path).convert('RGB')
        
        if self.transform:
            image = self.transform(image)
            
        return image, label

# ==========================================
# 4. MODEL BUILDER
# ==========================================

def get_model(model_name, num_classes=2):
    """
    Build one of the 5 pretrained models with a Dropout(0.3) + Linear(2) classification head.
    """
    if model_name == 'ResNet50':
        weights = models.ResNet50_Weights.DEFAULT
        model = models.resnet50(weights=weights)
        in_features = model.fc.in_features
        model.fc = nn.Sequential(
            nn.Dropout(0.3),
            nn.Linear(in_features, num_classes)
        )
    elif model_name == 'EfficientNet-B0':
        weights = models.EfficientNet_B0_Weights.DEFAULT
        model = models.efficientnet_b0(weights=weights)
        in_features = model.classifier[1].in_features
        model.classifier = nn.Sequential(
            nn.Dropout(0.3),
            nn.Linear(in_features, num_classes)
        )
    elif model_name == 'MobileNetV2':
        weights = models.MobileNet_V2_Weights.DEFAULT
        model = models.mobilenet_v2(weights=weights)
        in_features = model.classifier[1].in_features
        model.classifier = nn.Sequential(
            nn.Dropout(0.3),
            nn.Linear(in_features, num_classes)
        )
    elif model_name == 'ConvNeXt-Tiny':
        weights = models.ConvNeXt_Tiny_Weights.DEFAULT
        model = models.convnext_tiny(weights=weights)
        in_features = model.classifier[2].in_features
        model.classifier[2] = nn.Sequential(
            nn.Dropout(0.3),
            nn.Linear(in_features, num_classes)
        )
    elif model_name == 'Swin-Tiny':
        weights = models.Swin_T_Weights.DEFAULT
        model = models.swin_t(weights=weights)
        in_features = model.head.in_features
        model.head = nn.Sequential(
            nn.Dropout(0.3),
            nn.Linear(in_features, num_classes)
        )
    else:
        raise ValueError(f"Unknown model architecture: {model_name}")
    return model

# ==========================================
# 5. GRAD-CAM UTILITY
# ==========================================

class GradCAM:
    """
    Hook-based Grad-CAM implementation for CNN architectures.
    """
    def __init__(self, model, target_layer):
        self.model = model
        self.target_layer = target_layer
        self.activations = None
        self.gradients = None
        self.handlers = []
        
        # Register hooks
        self.handlers.append(target_layer.register_forward_hook(self._forward_hook))
        self.handlers.append(target_layer.register_full_backward_hook(self._backward_hook))
        
    def _forward_hook(self, module, input, output):
        self.activations = output.detach()
        
    def _backward_hook(self, module, grad_input, grad_output):
        self.gradients = grad_output[0].detach()
        
    def generate(self, input_tensor, class_idx=1):
        self.model.zero_grad()
        output = self.model(input_tensor)
        
        loss = output[0, class_idx]
        loss.backward()
        
        grads = self.gradients[0]
        acts = self.activations[0]
        
        # Global average pooling of gradients
        weights = torch.mean(grads, dim=[1, 2])
        
        # Weighted combination of activations
        cam = torch.zeros(acts.shape[1:], dtype=torch.float32, device=acts.device)
        for i, w in enumerate(weights):
            cam += w * acts[i, :, :]
            
        cam = F.relu(cam)
        cam = cam.cpu().numpy()
        
        # Min-max normalization
        cam_min, cam_max = cam.min(), cam.max()
        if cam_max > cam_min:
            cam = (cam - cam_min) / (cam_max - cam_min)
        else:
            cam = np.zeros_like(cam)
            
        return cam
        
    def remove_hooks(self):
        for h in self.handlers:
            h.remove()

def get_gradcam_layer(model_name, model):
    """
    Helper function to dynamically identify and return the target convolutional
    layer for Grad-CAM.
    """
    if model_name == 'ResNet50':
        return model.layer4[-1]
    elif model_name == 'EfficientNet-B0':
        return model.features[-1]
    elif model_name == 'MobileNetV2':
        return model.features[-1]
    elif model_name == 'ConvNeXt-Tiny':
        return model.features[-1][-1]
    return None

# ==========================================
# 6. DENORMALIZATION
# ==========================================

DENORM_MEAN = torch.tensor([0.485, 0.456, 0.406])
DENORM_STD = torch.tensor([0.229, 0.224, 0.225])

def denormalize(tensor):
    """
    Reverse ImageNet normalization for displaying original images.
    """
    t = tensor.clone().cpu()
    t = t * DENORM_STD[:, None, None] + DENORM_MEAN[:, None, None]
    return t.permute(1, 2, 0).numpy().clip(0, 1)

# ==========================================
# 7. MAIN PIPELINE EXECUTION
# ==========================================

def run_pipeline(args):
    # Setup directories
    save_dir = Path(args.save_dir)
    save_dir.mkdir(parents=True, exist_ok=True)
    
    device = torch.device(args.device if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")
    
    # ── Preprocessing & Data Loading ──
    print("\nLoading data...")
    df_gt = pd.read_csv(args.csv_path)
    
    # Class mapping: Malignant (MEL, BCC, AK, SCC) vs Benign (NV, BKL, DF, VASC)
    MALIGNANT_COLS = ['MEL', 'BCC', 'AK', 'SCC']
    df_gt['label'] = 0
    for col in MALIGNANT_COLS:
        if col in df_gt.columns:
            df_gt.loc[df_gt[col] == 1, 'label'] = 1
            
    # Load metadata if exists for GroupShuffleSplit
    metadata_path = Path(args.meta_path)
    if metadata_path.exists():
        df_meta = pd.read_csv(metadata_path)
        df = pd.merge(df_gt, df_meta, on='image', how='inner')
        print(f"Metadata loaded. Total rows: {len(df)}")
    else:
        df = df_gt.copy()
        print("Metadata file not found. Falling back to GroundTruth only.")
        
    # Strict 70/15/15 split using GroupShuffleSplit if lesion_id exists
    if 'lesion_id' in df.columns:
        print("Performing GroupShuffleSplit using 'lesion_id' to prevent data leakage...")
        gss1 = GroupShuffleSplit(n_splits=1, test_size=0.15, random_state=42)
        train_full_idx, test_idx = next(gss1.split(df, groups=df['lesion_id']))
        df_train_full = df.iloc[train_full_idx].reset_index(drop=True)
        df_test = df.iloc[test_idx].reset_index(drop=True)
        
        # Split train_full into train (70%) and val (15%)
        val_rel_size = 0.15 / 0.85
        gss2 = GroupShuffleSplit(n_splits=1, test_size=val_rel_size, random_state=42)
        train_idx, val_idx = next(gss2.split(df_train_full, groups=df_train_full['lesion_id']))
        df_train_raw = df_train_full.iloc[train_idx].reset_index(drop=True)
        df_val = df_train_full.iloc[val_idx].reset_index(drop=True)
    else:
        print("Performing standard stratified Train/Validation/Test split...")
        df_train_full, df_test = train_test_split(df, test_size=0.15, random_state=42, stratify=df['label'])
        df_train_raw, df_val = train_test_split(df_train_full, test_size=0.1765, random_state=42, stratify=df_train_full['label'])
        
    print(f"Original splits:")
    print(f"  Train (raw): {len(df_train_raw)} (Malignant: {(df_train_raw['label'] == 1).sum()}, Benign: {(df_train_raw['label'] == 0).sum()})")
    print(f"  Val:         {len(df_val)} (Malignant: {(df_val['label'] == 1).sum()}, Benign: {(df_val['label'] == 0).sum()})")
    print(f"  Test:        {len(df_test)} (Malignant: {(df_test['label'] == 1).sum()}, Benign: {(df_test['label'] == 0).sum()})")
    
    # Undersample Benign in training set to achieve 50:50 ratio
    df_train_benign = df_train_raw[df_train_raw['label'] == 0]
    df_train_malignant = df_train_raw[df_train_raw['label'] == 1]
    
    n_malignant = len(df_train_malignant)
    df_train_benign_under = df_train_benign.sample(n=n_malignant, random_state=42)
    df_train = pd.concat([df_train_benign_under, df_train_malignant]).sample(frac=1, random_state=42).reset_index(drop=True)
    
    print(f"\nTraining set after 50:50 undersampling:")
    print(f"  Total: {len(df_train)} (Malignant: {(df_train['label'] == 1).sum()}, Benign: {(df_train['label'] == 0).sum()})")
    
    # ── PyTorch v2 Transforms ──
    train_transforms = v2.Compose([
        v2.ToImage(),
        v2.Resize((224, 224), antialias=True),
        v2.RandomHorizontalFlip(p=0.5),
        v2.RandomVerticalFlip(p=0.5),
        v2.RandomRotation(degrees=15),
        v2.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1),
        v2.RandAugment(num_ops=2, magnitude=9),
        v2.ToDtype(torch.float32, scale=True),
        v2.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    
    val_test_transforms = v2.Compose([
        v2.ToImage(),
        v2.Resize((224, 224), antialias=True),
        v2.ToDtype(torch.float32, scale=True),
        v2.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    
    # Mixup and Cutmix loaders
    cutmix = v2.CutMix(num_classes=2)
    mixup = v2.MixUp(num_classes=2, alpha=0.4)
    cutmix_or_mixup = v2.RandomChoice([cutmix, mixup])
    
    train_dataset = ISICDataset(df_train, args.img_dir, train_transforms)
    val_dataset = ISICDataset(df_val, args.img_dir, val_test_transforms)
    test_dataset = ISICDataset(df_test, args.img_dir, val_test_transforms)
    
    train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True, num_workers=args.num_workers, pin_memory=True)
    val_loader = DataLoader(val_dataset, batch_size=args.batch_size, shuffle=False, num_workers=args.num_workers, pin_memory=True)
    test_loader = DataLoader(test_dataset, batch_size=args.batch_size, shuffle=False, num_workers=args.num_workers, pin_memory=True)
    
    # ── Augmentation Grid ──
    print("\nGenerating Preprocessing Augmentation Grid...")
    fig, axes = plt.subplots(4, 4, figsize=(12, 12))
    
    # Draw a sample image and apply augmentations manually for display
    raw_sample_df = df_train.head(4)
    for idx, (_, row) in enumerate(raw_sample_df.iterrows()):
        img_name = row['image']
        label = row['label']
        for ext in ['.jpg', '.jpeg', '.png', '.JPG']:
            path = Path(args.img_dir) / (img_name + ext)
            if path.exists():
                break
        img_pil = Image.open(path).convert('RGB')
        img_resized = img_pil.resize((224, 224))
        
        # Column 0: Original
        axes[idx, 0].imshow(img_resized)
        axes[idx, 0].set_title(f"Original ({'Mal' if label==1 else 'Ben'})", fontsize=9)
        axes[idx, 0].axis('off')
        
        # Column 1: RandAugment
        img_aug_tensor = train_transforms(img_pil)
        img_aug_np = denormalize(img_aug_tensor)
        axes[idx, 1].imshow(img_aug_np)
        axes[idx, 1].set_title("RandAugment", fontsize=9)
        axes[idx, 1].axis('off')
        
    # Get a batch of images to generate CutMix and MixUp
    images_batch, labels_batch = next(iter(DataLoader(train_dataset, batch_size=4, shuffle=True)))
    
    # Apply CutMix
    images_cutmix, labels_cutmix = cutmix(images_batch.clone(), labels_batch.clone())
    # Apply MixUp
    images_mixup, labels_mixup = mixup(images_batch.clone(), labels_batch.clone())
    
    for idx in range(4):
        # Column 2: CutMix
        axes[idx, 2].imshow(denormalize(images_cutmix[idx]))
        axes[idx, 2].set_title("CutMix Batch", fontsize=9)
        axes[idx, 2].axis('off')
        
        # Column 3: MixUp
        axes[idx, 3].imshow(denormalize(images_mixup[idx]))
        axes[idx, 3].set_title("MixUp Batch", fontsize=9)
        axes[idx, 3].axis('off')
        
    plt.suptitle("ISIC 2019 — Preprocessing and Augmentation Pipeline", fontsize=14, fontweight='bold', y=0.98)
    plt.tight_layout()
    plt.savefig(save_dir / 'augmentation_grid.png', dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Augmentation grid saved to {save_dir / 'augmentation_grid.png'}")
    
    # ── Class-weighted Loss & Setup ──
    # Compute class weights based on the undersampled training split (which is 50:50, so weights will be equal 1.0,
    # but we write the computation dynamically for completeness/reproducibility)
    n_b = (df_train['label'] == 0).sum()
    n_m = (df_train['label'] == 1).sum()
    total_train = len(df_train)
    
    w_b = total_train / (2 * n_b)
    w_m = total_train / (2 * n_m)
    class_weights = torch.tensor([w_b, w_m], dtype=torch.float).to(device)
    print(f"\nClass weights (Benign vs Malignant): {class_weights.cpu().numpy()}")
    
    criterion = WeightedSoftCELoss(weight=class_weights, label_smoothing=0.1)
    
    # ── Train All 5 Models ──
    models_to_train = ['ResNet50', 'EfficientNet-B0', 'MobileNetV2', 'ConvNeXt-Tiny', 'Swin-Tiny']
    trained_models = {}
    histories = {}
    
    for model_name in models_to_train:
        print(f"\n==========================================")
        print(f" Training Model: {model_name}")
        print(f"==========================================")
        
        model = get_model(model_name).to(device)
        
        # LR setup (Swin-Tiny needs smaller LR, Swin weight decay is typically larger)
        if model_name == 'Swin-Tiny':
            lr = 5e-5
            weight_decay = 0.01
        else:
            lr = 1e-4
            weight_decay = 1e-4
            
        optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)
        scheduler = CosineAnnealingLR(optimizer, T_max=args.epochs, eta_min=1e-6)
        scaler = GradScaler(enabled=True) # AMP GradScaler
        
        best_val_loss = float('inf')
        best_model_wts = copy.deepcopy(model.state_dict())
        patience_counter = 0
        
        history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}
        
        for epoch in range(1, args.epochs + 1):
            # ── Training Loop ──
            model.train()
            running_loss = 0.0
            corrects = 0
            total = 0
            
            for images, labels in train_loader:
                images = images.to(device)
                labels = labels.to(device)
                
                # Apply CutMix/MixUp dynamically with 50% probability
                if random.random() < 0.5:
                    images, targets = cutmix_or_mixup(images, labels)
                else:
                    targets = F.one_hot(labels, num_classes=2).float()
                    
                optimizer.zero_grad()
                
                # AMP Autocast
                with autocast(enabled=True):
                    outputs = model(images)
                    loss = criterion(outputs, targets)
                    
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()
                
                running_loss += loss.item() * images.size(0)
                preds = outputs.argmax(dim=-1)
                
                # Correct count computed against standard label
                corrects += (preds == labels).sum().item()
                total += labels.size(0)
                
            train_loss = running_loss / total
            train_acc = corrects / total
            
            # ── Validation Loop ──
            model.eval()
            val_loss_sum = 0.0
            val_corrects = 0
            val_total = 0
            
            with torch.no_grad():
                for images, labels in val_loader:
                    images = images.to(device)
                    labels = labels.to(device)
                    
                    with autocast(enabled=True):
                        outputs = model(images)
                        loss = criterion(outputs, labels)
                        
                    val_loss_sum += loss.item() * images.size(0)
                    preds = outputs.argmax(dim=-1)
                    val_corrects += (preds == labels).sum().item()
                    val_total += labels.size(0)
                    
            val_loss = val_loss_sum / val_total
            val_acc = val_corrects / val_total
            
            scheduler.step()
            
            history['train_loss'].append(train_loss)
            history['val_loss'].append(val_loss)
            history['train_acc'].append(train_acc)
            history['val_acc'].append(val_acc)
            
            print(f"Epoch {epoch}/{args.epochs} — Train Loss: {train_loss:.4f} Acc: {train_acc:.4f} | Val Loss: {val_loss:.4f} Acc: {val_acc:.4f}")
            
            # Early stopping on validation loss
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                best_model_wts = copy.deepcopy(model.state_dict())
                patience_counter = 0
            else:
                patience_counter += 1
                if patience_counter >= args.patience:
                    print(f"Early stopping triggered at epoch {epoch}")
                    break
                    
        # Load best weights
        model.load_state_dict(best_model_wts)
        trained_models[model_name] = model
        histories[model_name] = history
        
        # Save model checkpoint
        safe_name = model_name.lower().replace('-', '_')
        torch.save(best_model_wts, save_dir / f"best_{safe_name}.pth")
        print(f"Model saved: {save_dir / f'best_{safe_name}.pth'}")
        
    # ── Generate Training Loss Curves ──
    fig, axes = plt.subplots(2, 3, figsize=(16, 10))
    axes = axes.flatten()
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']
    
    for idx, model_name in enumerate(models_to_train):
        ax = axes[idx]
        hist = histories[model_name]
        epochs = range(1, len(hist['train_loss']) + 1)
        ax.plot(epochs, hist['train_loss'], color=colors[idx], linewidth=2, label='Train Loss')
        ax.plot(epochs, hist['val_loss'], color=colors[idx], linewidth=2, linestyle='--', label='Val Loss')
        ax.set_title(model_name, fontsize=12, fontweight='bold')
        ax.set_xlabel('Epoch')
        ax.set_ylabel('Loss')
        ax.legend()
        ax.grid(True, alpha=0.3)
        
    # Clear empty subplot
    axes[5].axis('off')
    plt.suptitle("Training & Validation Loss Curves (Stage 1 Binary Classification)", fontsize=15, fontweight='bold', y=1.01)
    plt.tight_layout()
    plt.savefig(save_dir / 'loss_curves.png', dpi=300, bbox_inches='tight')
    plt.close()
    
    # ── Evaluation Utility ──
    def get_predictions(model, loader):
        model.eval()
        all_probs = []
        all_labels = []
        with torch.no_grad():
            for images, labels in loader:
                images = images.to(device)
                with autocast(enabled=True):
                    outputs = model(images)
                    probs = torch.softmax(outputs, dim=-1)[:, 1]
                all_probs.extend(probs.cpu().numpy())
                all_labels.extend(labels.numpy())
        return np.array(all_probs), np.array(all_labels)
        
    # Get validation probabilities for clinical threshold sweep
    val_probs_dict = {}
    val_labels = None
    
    print("\nEvaluating individual models on Validation Set...")
    for model_name, model in trained_models.items():
        probs, labels = get_predictions(model, val_loader)
        val_probs_dict[model_name] = probs
        val_labels = labels
        
    # Compute Ensemble validation probabilities (arithmetic mean)
    val_ens_probs = np.stack(list(val_probs_dict.values()), axis=0).mean(axis=0)
    
    # Sweep clinical thresholds on validation set
    thresholds = np.arange(0.01, 0.99, 0.01)
    clinical_threshold = 0.50
    best_spec = 0.0
    
    for t in thresholds:
        preds = (val_ens_probs >= t).astype(int)
        sens = recall_score(val_labels, preds, pos_label=1, zero_division=0)
        spec = recall_score(val_labels, preds, pos_label=0, zero_division=0)
        
        # Check sensitivity constraint
        if sens >= 0.90:
            if spec > best_spec:
                best_spec = spec
                clinical_threshold = t
                
    print(f"\nClinical Threshold Sweep Result:")
    print(f"  Selected threshold: {clinical_threshold:.2f} (achieves validation Sensitivity >= 0.90)")
    
    # Get test probabilities
    test_probs_dict = {}
    test_labels = None
    
    print("\nEvaluating individual models on Test Set...")
    for model_name, model in trained_models.items():
        probs, labels = get_predictions(model, test_loader)
        test_probs_dict[model_name] = probs
        test_labels = labels
        
        # Log individual test AUC for dynamic targeted Grad-CAM selection
        auc = roc_auc_score(labels, probs)
        print(f"  {model_name} Test AUC: {auc:.4f}")
        
    # Ensemble soft probabilities (arithmetic mean)
    test_ens_probs = np.stack(list(test_probs_dict.values()), axis=0).mean(axis=0)
    
    # ── Test Set Metrics Evaluation ──
    def compute_metrics(probs, labels, threshold):
        preds = (probs >= threshold).astype(int)
        acc = accuracy_score(labels, preds)
        prec = precision_score(labels, preds, zero_division=0)
        rec_mal = recall_score(labels, preds, pos_label=1, zero_division=0) # Sensitivity
        rec_ben = recall_score(labels, preds, pos_label=0, zero_division=0) # Specificity
        f1 = f1_score(labels, preds, zero_division=0)
        auc = roc_auc_score(labels, probs)
        return {
            'Accuracy': acc,
            'Precision': prec,
            'F1-Score': f1,
            'AUC': auc,
            'Sensitivity': rec_mal,
            'Specificity': rec_ben
        }
        
    metrics_default = compute_metrics(test_ens_probs, test_labels, 0.50)
    metrics_clinical = compute_metrics(test_ens_probs, test_labels, clinical_threshold)
    
    print("\n==========================================")
    print(" FINAL ENSEMBLE TEST SET RESULTS")
    print("==========================================")
    print(f"  {'Metric':<15} | {'Default (0.50)':<15} | {f'Clinical ({clinical_threshold:.2f})':<15}")
    print("-" * 55)
    for key in metrics_default:
        print(f"  {key:<15} | {metrics_default[key]:<15.4f} | {metrics_clinical[key]:<15.4f}")
    print("==========================================")
    
    # Save metrics to text report
    with open(save_dir / 'metrics_summary.txt', 'w') as f:
        f.write("=== FINAL ENSEMBLE TEST SET RESULTS ===\n")
        f.write(f"  {'Metric':<15} | {'Default (0.50)':<15} | {f'Clinical ({clinical_threshold:.2f})':<15}\n")
        f.write("-" * 55 + "\n")
        for key in metrics_default:
            f.write(f"  {key:<15} | {metrics_default[key]:<15.4f} | {metrics_clinical[key]:<15.4f}\n")
            
    # ── Confusion Matrices ──
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    
    for idx, (thresh, title, m_dict) in enumerate([
        (0.50, "Ensemble @ Default (0.50)", metrics_default),
        (clinical_threshold, f"Ensemble @ Clinical ({clinical_threshold:.2f})", metrics_clinical)
    ]):
        preds = (test_ens_probs >= thresh).astype(int)
        cm = confusion_matrix(test_labels, preds)
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[idx],
                    xticklabels=['Benign', 'Malignant'], yticklabels=['Benign', 'Malignant'],
                    cbar=False, annot_kws={"size": 14, "weight": "bold"})
        axes[idx].set_title(f"{title}\nSens: {m_dict['Sensitivity']:.3f} | Spec: {m_dict['Specificity']:.3f}", fontsize=12, fontweight='bold')
        axes[idx].set_xlabel('Predicted Label')
        axes[idx].set_ylabel('True Label')
        
    plt.suptitle("Final Ensemble Confusion Matrices on Test Set", fontsize=14, fontweight='bold')
    plt.tight_layout()
    plt.savefig(save_dir / 'confusion_matrices.png', dpi=300, bbox_inches='tight')
    plt.close()
    
    # ── ROC Curve ──
    plt.figure(figsize=(7, 6))
    fpr, tpr, _ = roc_curve(test_labels, test_ens_probs)
    plt.plot(fpr, tpr, color='#e74c3c', linewidth=2.5, label=f"Ensemble (AUC = {metrics_default['AUC']:.4f})")
    plt.plot([0, 1], [0, 1], 'k--', alpha=0.5)
    
    # Plot default operating point
    fpr_def = 1 - metrics_default['Specificity']
    tpr_def = metrics_default['Sensitivity']
    plt.scatter(fpr_def, tpr_def, color='blue', s=100, zorder=5, label=f"Default (Thresh=0.50)")
    
    # Plot clinical operating point
    fpr_clin = 1 - metrics_clinical['Specificity']
    tpr_clin = metrics_clinical['Sensitivity']
    plt.scatter(fpr_clin, tpr_clin, color='green', s=100, zorder=5, label=f"Clinical (Thresh={clinical_threshold:.2f})")
    
    plt.xlim([-0.01, 1.01])
    plt.ylim([-0.01, 1.01])
    plt.xlabel('False Positive Rate (1 - Specificity)', fontsize=11)
    plt.ylabel('True Positive Rate (Sensitivity)', fontsize=11)
    plt.title('ROC Curve of Final Soft-Voting Ensemble on Test Set', fontsize=12, fontweight='bold')
    plt.legend(loc='lower right', fontsize=10)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(save_dir / 'roc_curve.png', dpi=300, bbox_inches='tight')
    plt.close()
    
    # ── Targeted Grad-CAM ──
    # Dynamically select the single top CNN model based on individual validation AUC
    print("\nDynamic CNN Model Selection for Targeted Grad-CAM...")
    cnn_names = ['ResNet50', 'EfficientNet-B0', 'MobileNetV2', 'ConvNeXt-Tiny']
    best_cnn_name = None
    best_cnn_auc = 0.0
    
    for cnn in cnn_names:
        # Calculate Validation AUC
        auc = roc_auc_score(val_labels, val_probs_dict[cnn])
        print(f"  {cnn} Validation AUC: {auc:.4f}")
        if auc > best_cnn_auc:
            best_cnn_auc = auc
            best_cnn_name = cnn
            
    print(f"Top CNN Selected: {best_cnn_name} (Validation AUC = {best_cnn_auc:.4f})")
    
    top_model = trained_models[best_cnn_name]
    target_layer = get_gradcam_layer(best_cnn_name, top_model)
    
    # Collect 4 malignant sample images from test loader for Grad-CAM visualization
    sample_images = []
    sample_labels = []
    for images, labels in test_loader:
        for img, lbl in zip(images, labels):
            if int(lbl) == 1: # Malignant
                sample_images.append(img)
                sample_labels.append(int(lbl))
            if len(sample_images) >= 4:
                break
        if len(sample_images) >= 4:
            break
            
    fig, axes = plt.subplots(2, 4, figsize=(14, 8))
    gcam = GradCAM(top_model, target_layer)
    
    for idx, (img_tensor, lbl) in enumerate(zip(sample_images, sample_labels)):
        # Denormalize image for correct display
        orig_img = denormalize(img_tensor)
        
        # Generate Grad-CAM activation map
        cam_map = gcam.generate(img_tensor.unsqueeze(0).to(device), class_idx=1)
        
        # Resize cam_map to input size (224, 224)
        cam_resized = np.array(Image.fromarray(cam_map).resize((224, 224), Image.Resampling.BILINEAR))
        
        # Overlay heatmap on original image
        heatmap = cm.jet(cam_resized)[:, :, :3]
        overlay = (0.55 * orig_img + 0.45 * heatmap).clip(0, 1)
        
        # Predict class & probability for displaying
        top_model.eval()
        with torch.no_grad():
            with autocast(enabled=True):
                logit = top_model(img_tensor.unsqueeze(0).to(device))
                prob = torch.softmax(logit, dim=-1)[0, 1].item()
                
        pred_lbl = "Malignant" if prob >= clinical_threshold else "Benign"
        correct = "✓" if pred_lbl == "Malignant" else "✗"
        
        # Plot Original Image
        axes[0, idx].imshow(orig_img)
        axes[0, idx].set_title(f"Original test {idx+1}\nTrue: Malignant", fontsize=10)
        axes[0, idx].axis('off')
        
        # Plot Grad-CAM Overlay
        axes[1, idx].imshow(overlay)
        axes[1, idx].set_title(f"Grad-CAM ({best_cnn_name})\nP(Mal)={prob:.2f} → {pred_lbl} {correct}", fontsize=9)
        axes[1, idx].axis('off')
        
    gcam.remove_hooks()
    
    plt.suptitle(f"Grad-CAM Heatmaps using Top CNN Model: {best_cnn_name}", fontsize=14, fontweight='bold', y=0.98)
    plt.tight_layout()
    plt.savefig(save_dir / 'grad_cam.png', dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Grad-CAM heatmaps saved to {save_dir / 'grad_cam.png'}")
    print("\nEnd-to-End Pipeline Executed Successfully!")

if __name__ == '__main__':
    # Parse CLI arguments with smart environment detections
    if os.path.exists('/kaggle/input/isic-2019'):
        default_csv = '/kaggle/input/isic-2019/ISIC_2019_Training_GroundTruth.csv'
        default_img = '/kaggle/input/isic-2019/ISIC_2019_Training_Input'
        default_meta = '/kaggle/input/isic-2019/ISIC_2019_Training_Metadata.csv'
    elif os.path.exists('d:/RESEARCH PNGS/data'):
        default_csv = 'd:/RESEARCH PNGS/data/ISIC_2019_Training_GroundTruth.csv'
        default_img = 'd:/RESEARCH PNGS/data/ISIC_2019_Training_Input'
        default_meta = 'd:/RESEARCH PNGS/data/ISIC_2019_Training_Metadata.csv'
    else:
        default_csv = './data/ISIC_2019_Training_GroundTruth.csv'
        default_img = './data/ISIC_2019_Training_Input'
        default_meta = './data/ISIC_2019_Training_Metadata.csv'
        
    parser = argparse.ArgumentParser(description="Reproducible ISIC 2019 Binary Classification Pipeline")
    parser.add_argument('--csv_path', type=str, default=default_csv, help="Path to Training GroundTruth CSV")
    parser.add_argument('--meta_path', type=str, default=default_meta, help="Path to Training Metadata CSV")
    parser.add_argument('--img_dir', type=str, default=default_img, help="Path to Training Input Images directory")
    parser.add_argument('--save_dir', type=str, default='./results/stage1', help="Directory to save checkpoint weights & figures")
    parser.add_argument('--epochs', type=str, default=20, help="Number of training epochs per model")
    parser.add_argument('--batch_size', type=int, default=32, help="DataLoader batch size")
    parser.add_argument('--patience', type=int, default=7, help="Early stopping patience")
    parser.add_argument('--num_workers', type=int, default=4, help="Number of workers for data loaders")
    parser.add_argument('--device', type=str, default='cuda', help="Target device (cuda or cpu)")
    
    args = parser.parse_args()
    
    # Cast epochs to int
    args.epochs = int(args.epochs)
    
    run_pipeline(args)
